name: Issue Notifications

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]
  # Optional: Add batch checking for reactions
  schedule:
    - cron: "0 * * * *" # Every hour

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Notification Action
        uses: joshdholtz/github-action-issue-ack@v16
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title_keywords: "urgent,security,bug"
          excluded_labels: "acknowledged"
          reaction_threshold: "5"
          comment_threshold: "3"
          # Enable batch checking for reactions
          check_all_open_issues: "true"
